IF OBJECT_ID(N'dbo.Acciones', N'U') IS NULL
CREATE TABLE dbo.Acciones (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Nombre NVARCHAR(100) NOT NULL,
  Descripcion NVARCHAR(255) NULL,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
